<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create categories
        $categories = [
            [
                'name' => 'Cakes',
                'slug' => 'cakes',
                'description' => 'Delicious handcrafted cakes for all occasions',
                'is_active' => true,
            ],
            [
                'name' => 'Cupcakes',
                'slug' => 'cupcakes',
                'description' => 'Individual portion cupcakes with gourmet frosting',
                'is_active' => true,
            ],
            [
                'name' => 'Pastries',
                'slug' => 'pastries',
                'description' => 'French-inspired pastries and sweet treats',
                'is_active' => true,
            ],
            [
                'name' => 'Desserts',
                'slug' => 'desserts',
                'description' => 'Classic desserts made with premium ingredients',
                'is_active' => true,
            ],
        ];

        foreach ($categories as $categoryData) {
            Category::create($categoryData);
        }

        $cakes = Category::where('slug', 'cakes')->first();
        $cupcakes = Category::where('slug', 'cupcakes')->first();
        $pastries = Category::where('slug', 'pastries')->first();
        $desserts = Category::where('slug', 'desserts')->first();

        $products = [
            [
                'category_id' => $cakes->id,
                'name' => 'White Cake',
                'slug' => 'white-cake',
                'description' => 'A classic white cake with smooth vanilla frosting. Simple, elegant, and perfect for any occasion.',
                'price' => 35.00,
                'stock' => 10,
                'image' => '/images/products/white-cake.svg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Pink Cake',
                'slug' => 'pink-cake',
                'description' => 'A delightful pink cake with strawberry-infused layers and creamy frosting. Sweet and charming.',
                'price' => 38.00,
                'stock' => 10,
                'image' => '/images/products/pink-cake.svg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Purple Cake',
                'slug' => 'purple-cake',
                'description' => 'A vibrant purple cake with blueberry and lavender notes. Uniquely flavored and beautifully presented.',
                'price' => 42.00,
                'stock' => 10,
                'image' => '/images/products/purple-cake.svg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Red Cake',
                'slug' => 'red-cake',
                'description' => 'A bold red velvet cake with rich cream cheese frosting. A timeless favorite with stunning color.',
                'price' => 40.00,
                'stock' => 10,
                'image' => '/images/products/red-cake.svg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Blue Cake',
                'slug' => 'blue-cake',
                'description' => 'A dreamy blue cake with vanilla bean flavor and buttercream frosting. Perfect for celebrations.',
                'price' => 38.00,
                'stock' => 10,
                'image' => '/images/products/blue-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Green Cake',
                'slug' => 'green-cake',
                'description' => 'A fresh green cake with matcha and white chocolate layers. Earthy, sweet, and full of flavor.',
                'price' => 40.00,
                'stock' => 10,
                'image' => '/images/products/green-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Yellow Cake',
                'slug' => 'yellow-cake',
                'description' => 'A sunny yellow cake with lemon curd filling and vanilla buttercream. Bright, zesty, and joyful.',
                'price' => 36.00,
                'stock' => 10,
                'image' => '/images/products/yellow-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Orange Cake',
                'slug' => 'orange-cake',
                'description' => 'A citrusy orange cake with tangerine glaze and cream cheese frosting. Refreshing and aromatic.',
                'price' => 37.00,
                'stock' => 10,
                'image' => '/images/products/orange-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cupcakes->id,
                'name' => 'Lavender Cake',
                'slug' => 'lavender-cake',
                'description' => 'A soothing lavender cake with honey and vanilla notes. Fragrant, delicate, and unforgettable.',
                'price' => 44.00,
                'stock' => 8,
                'image' => '/images/products/lavender-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cupcakes->id,
                'name' => 'Mint Cake',
                'slug' => 'mint-cake',
                'description' => 'A cool mint cake with chocolate chips and mint buttercream. Refreshing with every bite.',
                'price' => 39.00,
                'stock' => 10,
                'image' => '/images/products/mint-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cupcakes->id,
                'name' => 'Coral Cake',
                'slug' => 'coral-cake',
                'description' => 'A warm coral cake with peach and raspberry filling. Tropical vibes in every slice.',
                'price' => 41.00,
                'stock' => 10,
                'image' => '/images/products/coral-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cupcakes->id,
                'name' => 'Peach Cake',
                'slug' => 'peach-cake',
                'description' => 'A soft peach cake with caramelized peach slices and whipped cream. Summer in a cake.',
                'price' => 38.00,
                'stock' => 10,
                'image' => '/images/products/peach-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $pastries->id,
                'name' => 'Teal Cake',
                'slug' => 'teal-cake',
                'description' => 'A striking teal cake with coconut and lime layers. Bold color meets tropical flavor.',
                'price' => 43.00,
                'stock' => 8,
                'image' => '/images/products/teal-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $pastries->id,
                'name' => 'Gold Cake',
                'slug' => 'gold-cake',
                'description' => 'A luxurious gold cake with salted caramel and toffee layers. Rich, indulgent, and show-stopping.',
                'price' => 52.00,
                'stock' => 6,
                'image' => '/images/products/gold-cake.svg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $pastries->id,
                'name' => 'Silver Cake',
                'slug' => 'silver-cake',
                'description' => 'An elegant silver cake with Earl Grey tea and vanilla bean. Sophisticated and subtly sweet.',
                'price' => 48.00,
                'stock' => 8,
                'image' => '/images/products/silver-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $pastries->id,
                'name' => 'Rose Cake',
                'slug' => 'rose-cake',
                'description' => 'A romantic rose cake with rosewater cream and pistachio crumble. Floral, nutty, and divine.',
                'price' => 46.00,
                'stock' => 8,
                'image' => '/images/products/rose-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $desserts->id,
                'name' => 'Sky Cake',
                'slug' => 'sky-cake',
                'description' => 'A light sky blue cake with cotton candy flavoring and cloud-like frosting. Whimsical and delicious.',
                'price' => 39.00,
                'stock' => 10,
                'image' => '/images/products/sky-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $desserts->id,
                'name' => 'Lime Cake',
                'slug' => 'lime-cake',
                'description' => 'A tangy lime cake with key lime curd and coconut cream. Zingy, tropical, and addictive.',
                'price' => 37.00,
                'stock' => 10,
                'image' => '/images/products/lime-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $desserts->id,
                'name' => 'Indigo Cake',
                'slug' => 'indigo-cake',
                'description' => 'A deep indigo cake with blackberry compote and vanilla mousse. Mysterious and deeply flavorful.',
                'price' => 45.00,
                'stock' => 8,
                'image' => '/images/products/indigo-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $desserts->id,
                'name' => 'Amber Cake',
                'slug' => 'amber-cake',
                'description' => 'A warm amber cake with maple syrup and brown butter frosting. Cozy, comforting, and rich.',
                'price' => 41.00,
                'stock' => 10,
                'image' => '/images/products/amber-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Cyan Cake',
                'slug' => 'cyan-cake',
                'description' => 'A bright cyan cake with blue curaçao and citrus notes. Eye-catching and refreshingly sweet.',
                'price' => 40.00,
                'stock' => 10,
                'image' => '/images/products/cyan-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Magenta Cake',
                'slug' => 'magenta-cake',
                'description' => 'A vivid magenta cake with dragonfruit and passion fruit filling. Exotic, bold, and irresistible.',
                'price' => 44.00,
                'stock' => 8,
                'image' => '/images/products/magenta-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Burgundy Cake',
                'slug' => 'burgundy-cake',
                'description' => 'A rich burgundy cake with red wine reduction and dark chocolate ganache. Decadent and refined.',
                'price' => 50.00,
                'stock' => 6,
                'image' => '/images/products/burgundy-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cupcakes->id,
                'name' => 'Navy Cake',
                'slug' => 'navy-cake',
                'description' => 'A deep navy cake with blueberry jam and mascarpone cream. Sophisticated and berry-forward.',
                'price' => 43.00,
                'stock' => 8,
                'image' => '/images/products/navy-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cupcakes->id,
                'name' => 'Olive Cake',
                'slug' => 'olive-cake',
                'description' => 'A unique olive cake with pistachio and lemon. Earthy, nutty, and surprisingly delightful.',
                'price' => 39.00,
                'stock' => 10,
                'image' => '/images/products/olive-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $pastries->id,
                'name' => 'Plum Cake',
                'slug' => 'plum-cake',
                'description' => 'A fragrant plum cake with spiced plum compote and cinnamon cream. Warm and seasonal.',
                'price' => 42.00,
                'stock' => 8,
                'image' => '/images/products/plum-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $pastries->id,
                'name' => 'Salmon Cake',
                'slug' => 'salmon-cake',
                'description' => 'A soft salmon-colored cake with guava and cream cheese filling. Tropical elegance on a plate.',
                'price' => 40.00,
                'stock' => 10,
                'image' => '/images/products/salmon-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $desserts->id,
                'name' => 'Turquoise Cake',
                'slug' => 'turquoise-cake',
                'description' => 'A gorgeous turquoise cake with pineapple and coconut layers. Island-inspired and irresistible.',
                'price' => 41.00,
                'stock' => 10,
                'image' => '/images/products/turquoise-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $desserts->id,
                'name' => 'Chocolate Cake',
                'slug' => 'chocolate-cake',
                'description' => 'A rich chocolate cake with double chocolate ganache and cocoa dusting. The ultimate chocolate indulgence.',
                'price' => 45.00,
                'stock' => 10,
                'image' => '/images/products/chocolate-cake.svg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Cream Cake',
                'slug' => 'cream-cake',
                'description' => 'A delicate cream cake with Bavarian cream and vanilla wafer crumble. Light, airy, and elegant.',
                'price' => 36.00,
                'stock' => 10,
                'image' => '/images/products/cream-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Ruby Cake',
                'slug' => 'ruby-cake',
                'description' => 'A dazzling ruby cake with raspberry coulis and white chocolate mousse. Jewel-toned and luxurious.',
                'price' => 48.00,
                'stock' => 6,
                'image' => '/images/products/ruby-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $cakes->id,
                'name' => 'Emerald Cake',
                'slug' => 'emerald-cake',
                'description' => 'A lush emerald cake with matcha, white chocolate, and mint. Green, gorgeous, and gourmet.',
                'price' => 46.00,
                'stock' => 8,
                'image' => '/images/products/emerald-cake.svg',
                'is_active' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $productData) {
            $slug = $productData['slug'];
            $productData['images'] = [
                "/images/products/{$slug}-2.svg",
                "/images/products/{$slug}-3.svg",
                "/images/products/{$slug}-4.svg",
            ];
            Product::create($productData);
        }
    }
}
